### ISSUE TITLE
Enable Content Reports for Repository Contributors

### ISSUE THREAD

**Issue by Amorpheuz** [devcpune/devcpune.github.io#3]
[Content Reports](https://docs.github.com/en/github/building-a-strong-community/managing-reported-content-in-your-organizations-repository) allow contributors to the repo to report abuse in the repository to the maintainers. Enabling them by following the [outlined steps](https://docs.github.com/en/github/building-a-strong-community/managing-how-contributors-report-abuse-in-your-organizations-repository) will allow DevC Pune to maintain a safer environment similar to the Facebook group.

More information related to this can be found [here](https://docs.github.com/en/github/building-a-strong-community/moderating-comments-and-conversations). These steps should be performed by the repository Admin.

**Comment by sangeetagupta2068** [comment]
@Amorpheuz thanks for pointing out! This issue has been resolved.

**Comment by sangeetagupta2068** [comment]
@Amorpheuz , thanks for putting this up. As per the instructions, I have enabled "Accept content reports from collaborators and prior contributors" for this repository.

**Comment by Amorpheuz** [comment]
That's awesome!
