### ISSUE TITLE
Create Issue template and Pull Request template

### ISSUE THREAD

**Issue by vj-codes** [devcpune/devcpune.github.io#6]
Currently there are no templates for Issues and Pull Requests to be created.It is very unsure if a contributor is suggesting a feature or reporting a bug . Creating templates will make the job easier.
Category for issues might be  Bug, Feature Request, Other which have issue description, steps to reproduce for bugs, solution alternatives, resources and screenshot sections as a must.
And a PR template must have the issue linked section and describe a solution section.
Both should have checklists respectively.
Any other inputs about templates are welcomed!

**Comment by vj-codes** [comment]
May I work on this?

**Comment by sayak-sarkar** [comment]
@vj-codes Sure! Simply assign the issue to yourself and send in a PR! :)

**Comment by viragumathe5** [comment]
Hey, @vj-codes and @sayak-sarkar, if you are not working on the issue shall I give it a try????

**Comment by vj-codes** [comment]
@viragumathe5 sure I forgot about this issue haha you can work on this!

**Comment by viragumathe5** [comment]
@sayak-sarkar and @vj-codes  I am sorry, I was unable to make a PR. I will be making PR today with priority.
Really sorry for the delay.

**Comment by viragumathe5** [comment]
Hey @vj-codes I have made the PR please review it as you get time 
Thank You

**Comment by Siddhant-K-code** [comment]
This Issue is resolved with #11 

We Can Close this
